fix for trailing comma
FiNCDeveloper/fincop pull request #4
Opened 2018-03-28 13:56 UTC by nabuchi

fincop入れて実行したら↓のエラー起きたので対応しました

https://github.com/bbatsov/rubocop/pull/5307
https://github.com/onk/onkcop/commit/1942502794aa03c410a27b60fe6c52a2f5caf59c

```
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in vendor/bundle/ruby/2.4.0/bundler/gems/fincop-2f20413784da/config/rubocop.yml, please update it)
```

2018-03-28 15:56 UTC, qsona commented
Enforceするほどかね? けつかんま

2018-03-29 02:11 UTC, ota42y commented
autocorrectきくので良いと思います。

2018-03-29 02:13 UTC, ota42y commented
このcopが入ったのは0.53.0なので、依存バージョンを53.0以上にし、バージョンを0.53.0.1にしてください。

https://github.com/garettarrowood/rubocop/blob/master/CHANGELOG.md#0530-2018-03-05

2018-03-29 02:13 UTC, ota42y requested changes
このcopが入ったのは0.53.0なので、依存バージョンを53.0以上にし、バージョンを0.53.0.1にしてください。

https://github.com/garettarrowood/rubocop/blob/master/CHANGELOG.md#0530-2018-03-05

2018-03-29 02:19 UTC, nabuchi commented
@ota42y 
レビューありがとうございます、修正しました。

2018-03-29 02:35 UTC, ota42y approved these changes

2018-03-29 04:07 UTC, merged